### ISSUE TITLE
Persentation 1: Recommendations

### ISSUE THREAD

**Issue by MrDataPsycho** [Akaxgt/ML-Exercises#1]
# Suggestion
- Slides are Too details, Provide some info and example
- Book is just a tool given, No need to mention about the book. 
- We should be intersted where Igen we apply in NLP no need to explain the Math or Examples
- It is unnecessary to explain SVD or PCA in Mathmatics
- Maximum likelihood explained little bit off: MLE is a objective function which is our goal to maximize the Likelihood to fit the best model.
- So Crossfold is used in Grid Search so you should more focus on how they are implemented
- There is better approach for Hyperparam Optim. using Optuna (Baysing Optimization) or other freworks like hyperopt
- More focus on NLP
- Lot of info on the Slides (You could move them in Appendix)

# Presentation Through Put:
**When you present always Turn your Video On, You are not engaging with out audiance. The most important chapter was 4th but you spent least amount of time for this chapter. Give opprtunity to audiance to ask some question.**

# LIked It: Visuals in the slide, metion of Application, Delivery of the start of some topic

**Comment by Akaxgt** [comment]
Made changes
